# Generated by Django 5.0.7 on 2024-08-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('rooms', 'Room'), ('experiences', 'Experiences')], max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
