# Generated by Django 5.0.7 on 2024-08-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_experiences_alter_review_rooms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rooms',
            new_name='room',
        ),
    ]
